/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

(* src = "/work/designs/edgeconv_top/src/edgeconv.v:8.1-50.10" *)
module edgeconv(clk, rst_n, valid_in, pixel_in, digit_out, valid_out);
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  (* force_downto = 32'd1 *)
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:36.32-36.58|/nix/store/sx2v0i73mn1ih2z1nk61pm9n5gjgpidy-yosys/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2 3" *)
  wire [4:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:36.31-36.64|/nix/store/sx2v0i73mn1ih2z1nk61pm9n5gjgpidy-yosys/bin/../share/yosys/techmap.v:420.23-420.24" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _078_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:9.19-9.22" *)
  input clk;
  wire clk;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:13.19-13.28" *)
  output [3:0] digit_out;
  wire [3:0] digit_out;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:20.15-20.24" *)
  reg [9:0] pixel_cnt;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:12.19-12.27" *)
  input [7:0] pixel_in;
  wire [7:0] pixel_in;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:21.15-21.25" *)
  reg [3:0] result_reg;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:10.19-10.24" *)
  input rst_n;
  wire rst_n;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:11.19-11.27" *)
  input valid_in;
  wire valid_in;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:14.19-14.28" *)
  output valid_out;
  wire valid_out;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:22.15-22.24" *)
  reg valid_reg;
  assign _001_ = ~pixel_cnt[0];
  assign _023_ = ~(result_reg[0] & pixel_in[0]);
  assign _024_ = result_reg[0] | pixel_in[0];
  assign _077_[0] = _023_ & _024_;
  assign _025_ = pixel_cnt[1] & pixel_cnt[0];
  assign _026_ = ~(pixel_cnt[1] | pixel_cnt[0]);
  assign _002_ = ~(_025_ | _026_);
  assign _027_ = pixel_cnt[2] & _025_;
  assign _028_ = ~(pixel_cnt[2] | _025_);
  assign _003_ = ~(_027_ | _028_);
  assign _029_ = pixel_cnt[3] & _027_;
  assign _030_ = ~(pixel_cnt[3] | _027_);
  assign _004_ = ~(_029_ | _030_);
  assign _031_ = pixel_cnt[4] & _029_;
  assign _032_ = ~(pixel_cnt[5] | pixel_cnt[4]);
  assign _033_ = ~(pixel_cnt[7] | pixel_cnt[6]);
  assign _034_ = pixel_cnt[8] & pixel_cnt[9];
  assign _035_ = _033_ & _034_;
  assign _036_ = _032_ & _035_;
  assign _037_ = ~(pixel_cnt[4] | _029_);
  assign _038_ = ~(_036_ | _037_);
  assign _005_ = _038_ & ~(_031_);
  assign _039_ = pixel_cnt[5] & _031_;
  assign _040_ = ~(pixel_cnt[5] | _031_);
  assign _006_ = ~(_039_ | _040_);
  assign _041_ = pixel_cnt[6] & _039_;
  assign _042_ = ~(pixel_cnt[6] | _039_);
  assign _007_ = ~(_041_ | _042_);
  assign _043_ = pixel_cnt[7] & _041_;
  assign _044_ = ~(pixel_cnt[7] | _041_);
  assign _008_ = ~(_043_ | _044_);
  assign _045_ = pixel_cnt[8] | _043_;
  assign _046_ = ~(_029_ & _036_);
  assign _047_ = ~(pixel_cnt[8] & _043_);
  assign _048_ = _045_ & _047_;
  assign _009_ = _046_ & _048_;
  assign _049_ = ~(pixel_cnt[9] & _047_);
  assign _050_ = pixel_cnt[9] | _047_;
  assign _051_ = ~(_049_ & _050_);
  assign _010_ = _046_ & _051_;
  assign _052_ = ~(result_reg[1] & pixel_in[1]);
  assign _053_ = result_reg[1] | pixel_in[1];
  assign _054_ = ~(_052_ & _053_);
  assign _055_ = _023_ | _054_;
  assign _056_ = ~(_023_ & _054_);
  assign _057_ = ~(_055_ & _056_);
  assign _058_ = ~(result_reg[2] & pixel_in[2]);
  assign _059_ = result_reg[2] | pixel_in[2];
  assign _060_ = _058_ & _059_;
  assign _061_ = ~(_052_ & _055_);
  assign _062_ = ~(_060_ & _061_);
  assign _063_ = ~(_058_ & _062_);
  assign _064_ = ~(result_reg[3] & pixel_in[3]);
  assign _065_ = result_reg[3] | pixel_in[3];
  assign _066_ = _064_ & _065_;
  assign _067_ = ~(_063_ & _066_);
  assign _068_ = _063_ | _066_;
  assign _069_ = _067_ & _068_;
  assign _070_ = ~(_064_ & _067_);
  assign _071_ = _060_ | _061_;
  assign _072_ = ~(_062_ & _071_);
  assign _073_ = _070_ & _072_;
  assign _074_ = _073_ & ~(_069_);
  assign _075_ = _069_ & ~(_073_);
  assign _076_ = ~(_069_ & _073_);
  assign _011_ = _070_ | _072_;
  assign _012_ = _076_ & _011_;
  assign _013_ = _057_ & _012_;
  assign _014_ = ~(_057_ & _012_);
  assign _015_ = _075_ & _014_;
  assign _016_ = _074_ | _015_;
  assign _017_ = ~(_057_ & _016_);
  assign _018_ = _057_ | _016_;
  assign _078_[1] = ~(_017_ & _018_);
  assign _019_ = ~(_074_ & _013_);
  assign _020_ = _012_ | ~(_017_);
  assign _078_[2] = ~(_019_ & _020_);
  assign _021_ = ~(_074_ & _014_);
  assign _022_ = ~(_075_ & _013_);
  assign _078_[3] = ~(_021_ & _022_);
  assign _000_ = valid_in & ~(_046_);
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result_reg[0] <= 1'h0;
    else if (valid_in) result_reg[0] <= _077_[0];
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result_reg[1] <= 1'h0;
    else if (valid_in) result_reg[1] <= _078_[1];
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result_reg[2] <= 1'h0;
    else if (valid_in) result_reg[2] <= _078_[2];
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result_reg[3] <= 1'h0;
    else if (valid_in) result_reg[3] <= _078_[3];
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[0] <= 1'h0;
    else if (valid_in) pixel_cnt[0] <= _001_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[1] <= 1'h0;
    else if (valid_in) pixel_cnt[1] <= _002_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[2] <= 1'h0;
    else if (valid_in) pixel_cnt[2] <= _003_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[3] <= 1'h0;
    else if (valid_in) pixel_cnt[3] <= _004_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[4] <= 1'h0;
    else if (valid_in) pixel_cnt[4] <= _005_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[5] <= 1'h0;
    else if (valid_in) pixel_cnt[5] <= _006_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[6] <= 1'h0;
    else if (valid_in) pixel_cnt[6] <= _007_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[7] <= 1'h0;
    else if (valid_in) pixel_cnt[7] <= _008_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[8] <= 1'h0;
    else if (valid_in) pixel_cnt[8] <= _009_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pixel_cnt[9] <= 1'h0;
    else if (valid_in) pixel_cnt[9] <= _010_;
  (* src = "/work/designs/edgeconv_top/src/edgeconv.v:24.5-45.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) valid_reg <= 1'h0;
    else valid_reg <= _000_;
  assign _077_[4] = 1'h0;
  assign _078_[0] = _077_[0];
  assign digit_out = result_reg;
  assign valid_out = valid_reg;
endmodule

(* top =  1  *)
(* src = "/work/designs/edgeconv_top/src/edgeconv_top.v:3.1-19.10" *)
module edgeconv_top(clk, rst_n, valid_in, pixel_in, digit_out, valid_out);
  (* src = "/work/designs/edgeconv_top/src/edgeconv_top.v:4.19-4.22" *)
  input clk;
  wire clk;
  (* src = "/work/designs/edgeconv_top/src/edgeconv_top.v:8.19-8.28" *)
  output [3:0] digit_out;
  wire [3:0] digit_out;
  (* src = "/work/designs/edgeconv_top/src/edgeconv_top.v:7.19-7.27" *)
  input [7:0] pixel_in;
  wire [7:0] pixel_in;
  (* src = "/work/designs/edgeconv_top/src/edgeconv_top.v:5.19-5.24" *)
  input rst_n;
  wire rst_n;
  (* src = "/work/designs/edgeconv_top/src/edgeconv_top.v:6.19-6.27" *)
  input valid_in;
  wire valid_in;
  (* src = "/work/designs/edgeconv_top/src/edgeconv_top.v:9.19-9.28" *)
  output valid_out;
  wire valid_out;
  (* module_not_derived = 32'd1 *)
  (* src = "/work/designs/edgeconv_top/src/edgeconv_top.v:11.14-18.6" *)
  edgeconv core (
    .clk(clk),
    .digit_out(digit_out),
    .pixel_in(pixel_in),
    .rst_n(rst_n),
    .valid_in(valid_in),
    .valid_out(valid_out)
  );
endmodule
